version: '3.9'

services:
  mageai:
    image: mageai/mageai:latest
    build:
      context: .
    command: mage start data_pipeline_demo
    environment:
      - ENV=dev
    ports:
      - 6789:6789
    volumes:
      - .:/home/src
    restart: on-failure:5
    stdin_open: true
    tty: true