version: '3.4'
 
services:
  airflow_base: &airflow_base
    image: data-pipeline-airflow-demo
    user: "${AIRFLOW_UID}:0"
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./pipelines:/opt/airflow/pipelines
      - ./seeds:/opt/airflow/seeds
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5434:5432"
    networks:
      - pipeline_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env
 
  scheduler:
    <<: *airflow_base
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"
    networks:
      - pipeline_network
 
  webserver:
    <<: *airflow_base
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    networks:
      - pipeline_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
   
  airflow-init:
    <<: *airflow_base
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    networks:
      - pipeline_network

  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      pipeline_network:
        ipv4_address: 10.5.0.5
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    env_file:
      - .env

  jupyter:
    image: data-pipeline-jupyter-demo
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_TOKEN=easy
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./seeds:/home/jovyan/seeds
    networks:
      - pipeline_network

networks:
  pipeline_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  minio_data:
    driver: local